### ISSUE TITLE
Upgrade contracts to ink! 4.0

### ISSUE THREAD

**Issue by HCastano** [RottenKiwi/Panorama-Swap-INK-SC#4]
Hi there!

Not sure how closely you follow our release cycle, but we released [ink! 4.0](https://github.com/paritytech/ink/releases/tag/v4.0.0) recently and it would probably be worth your time to update. We wrote a [migration guide](https://use.ink/faq/migrating-from-ink-3-to-4) to help out.
 
P.S, [_ink!_ is stylized](https://use.ink/faq#is-it-ink-or-ink-what-does-the--stand-for) as all lowercase and with the exclamation mark at the end, not in all caps 😉

**Comment by RottenKiwi** [comment]
Hey @HCastano,

Thank you for letting us know. 
We have upgraded our smart contract to the latest ink! 4.0 production version with no issues and we've change the how we write "ink!"

Bless you :)
